# Generated by Django 6.0.2 on 2026-03-14 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdBlog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
    ]
