# Generated by Django 6.0.2 on 2026-02-20 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdBlog', '0006_remove_post_stdblog_pos_publish_ef9183_idx_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='stdBlog_pos_publish_0bf573_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='stdBlog_pos_publish_ef9183_idx'),
        ),
    ]
