# Generated by Django 6.0.2 on 2026-02-20 09:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdBlog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publish',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 20, 9, 18, 31, 424773, tzinfo=datetime.timezone.utc)),
        ),
    ]
