# Generated by Django 6.0.2 on 2026-02-20 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stdBlog', '0003_post_created_post_updated_alter_post_publish'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish']},
        ),
    ]
