# Generated by Django 6.0.2 on 2026-02-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdBlog', '0004_alter_post_options'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='stdBlog_pos_publish_ef9183_idx'),
        ),
    ]
