# Generated by Django 6.0.2 on 2026-02-20 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stdBlog', '0005_post_stdblog_pos_publish_ef9183_idx'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='post',
            name='stdBlog_pos_publish_ef9183_idx',
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish', 'created'], name='stdBlog_pos_publish_0bf573_idx'),
        ),
    ]
